<a href="https://colab.research.google.com/github/Benjamin025/Benjamin025/blob/main/Nairobi%2C%20Kenya%20Houses%20Geocoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

In [ ]:
# Upload the Excel file to Colab or link to Google Drive
from google.colab import files
uploaded = files.upload()

Saving geocoded_output.csv to geocoded_output.csv

In [ ]:
# Load the CSV file instead of Excel
df = pd.read_csv('/content/geocoded_output.csv')  # Use pd.read_csv for CSV files

In [ ]:
df

,House,location,size,selling price,latitude,longitude
0,6 Bed Villa with En Suite at Kiambu Road,"Kiambu Road, Gathanji, Githunguri ward, Githun...","6bdrm Mansion in Mushroom Estate, Kiambu / Kia...","KSh 130,000,000",-1.085053,36.782040
1,4 Bed Townhouse with En Suite at Off Kiambu Road,NaN,4 Bedroom with DSQ for Sale,"KSh 26,950,000",NaN,NaN
2,4 Bed Villa with En Suite at Masai Lodge Road,"Rudolf Steiner School Ongata Rongai, Masai Lod...",New modern villa for sale.,"KSh 16,000,000",-1.391357,36.789061
3,5 Bed House with En Suite in Ngong Road,"Ngong Road, Ngong, Ngong ward, Kajiado North, ...",5 Bedroom Town House For Sale In Kilimani,"KSh 45,000,000",-1.360530,36.655977
4,5 Bed Townhouse with En Suite in Lavington,"Lavington, Albury, Albury City Council, New So...",Modern 5 Bedroom Townhouse For Sale,"KSh 72,000,000",-36.050799,146.933662
...,...,...,...,...,...,...
1871,5 Bed House with En Suite at Nandi Road,"Hartfield Hotel Karen, Nandi Road, Lenana subl...",5 BEDROOM HOUSE FOR SALE IN KAREN NAIROBI KENYA,"KSh 199,000,000",-1.316899,36.710539
1872,4 Bed House with En Suite in Kitengela,"Kitengela, Kitengela ward, Kajiado East, Rift ...",4 Bedroom Maisonette for Sale in Kitengela EPZ...,"KSh 16,000,000",-1.474564,36.959070
1873,4 Bed House with En Suite in Syokimau,"Syokimau, Mavoko, Machakos, Eastern, 74416, Kenya",4 BEDROOMS MAISONETTE IN SYOKIMAU.,"KSh 13,800,000",-1.377719,36.928529
1874,4 Bed Townhouse with Garden in Lavington,"Lavington, Albury, Albury City Council, New So...",4 bedroom townhouse for sale in Lavington,"KSh 79,000,000",-36.050799,146.933662
1875,3 Bed House with En Suite at Kimbo Matangi,NaN,READY AFFORDABLE BUNGALOWS ON OFFER,"KSh 7,800,000",NaN,NaN

In [ ]:
# Display the first few rows before cleaning
print("Before removing null values:")
print(df.head())

Before removing null values:
                                              House  \
0          6 Bed Villa with En Suite at Kiambu Road
1  4 Bed Townhouse with En Suite at Off Kiambu Road
2     4 Bed Villa with En Suite at Masai Lodge Road
3           5 Bed House with En Suite in Ngong Road
4        5 Bed Townhouse with En Suite in Lavington

                                            location  \
0  Kiambu Road, Gathanji, Githunguri ward, Githun...
1                                                NaN
2  Rudolf Steiner School Ongata Rongai, Masai Lod...
3  Ngong Road, Ngong, Ngong ward, Kajiado North, ...
4  Lavington, Albury, Albury City Council, New So...

                                                size    selling price  \
0  6bdrm Mansion in Mushroom Estate, Kiambu / Kia...  KSh 130,000,000
1                        4 Bedroom with DSQ for Sale   KSh 26,950,000
2                         New modern villa for sale.   KSh 16,000,000
3          5 Bedroom Town House For Sale In Kilimani   KSh 45,000,000
4                Modern 5 Bedroom Townhouse For Sale   KSh 72,000,000

    latitude   longitude
0  -1.085053   36.782040
1        NaN         NaN
2  -1.391357   36.789061
3  -1.360530   36.655977
4 -36.050799  146.933662

In [ ]:
# Remove rows where 'latitude' or 'longitude' contain NA values
df_cleaned = df.dropna(subset=['latitude', 'longitude'])

In [ ]:
# Display the cleaned DataFrame
print("\nAfter removing rows with null latitude/longitude:")
print(df_cleaned.head())

# Optional: Save the cleaned DataFrame to a new CSV file
df_cleaned.to_csv('cleaned_data.csv', index=False)

After removing rows with null latitude/longitude:
                                           House  \
0       6 Bed Villa with En Suite at Kiambu Road
2  4 Bed Villa with En Suite at Masai Lodge Road
3        5 Bed House with En Suite in Ngong Road
4     5 Bed Townhouse with En Suite in Lavington
6         5 Bed House with En Suite in Lavington

                                            location  \
0  Kiambu Road, Gathanji, Githunguri ward, Githun...
2  Rudolf Steiner School Ongata Rongai, Masai Lod...
3  Ngong Road, Ngong, Ngong ward, Kajiado North, ...
4  Lavington, Albury, Albury City Council, New So...
6  Lavington, Albury, Albury City Council, New So...

                                                size    selling price  \
0  6bdrm Mansion in Mushroom Estate, Kiambu / Kia...  KSh 130,000,000
2                         New modern villa for sale.   KSh 16,000,000
3          5 Bedroom Town House For Sale In Kilimani   KSh 45,000,000
4                Modern 5 Bedroom Townhouse For Sale   KSh 72,000,000
6  Rustic 5 Bedroom house For Sale on 1/4 of an a...   KSh 85,000,000

    latitude   longitude
0  -1.085053   36.782040
2  -1.391357   36.789061
3  -1.360530   36.655977
4 -36.050799  146.933662
6 -36.050799  146.933662

In [ ]:
df_cleaned.shape

(1355, 6)

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1355 entries, 0 to 1874
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   House          1355 non-null   object
 1   location       1355 non-null   object
 2   size           1355 non-null   object
 3   selling price  1355 non-null   object
 4   latitude       1355 non-null   float64
 5   longitude      1355 non-null   float64
dtypes: float64(2), object(4)
memory usage: 74.1+ KB

In [ ]:
df_cleaned.describe()

          latitude    longitude
count  1355.000000  1355.000000
mean     -4.157191    47.250250
std      13.403703    38.795839
min     -36.050799  -119.098584
25%      -1.475204    36.760646
50%      -1.314172    36.818415
75%      -1.218212    36.995683
max      51.240469   146.933662

In [ ]:
df_cleaned.head()

,House,location,size,selling price,latitude,longitude
0,6 Bed Villa with En Suite at Kiambu Road,"Kiambu Road, Gathanji, Githunguri ward, Githun...","6bdrm Mansion in Mushroom Estate, Kiambu / Kia...","KSh 130,000,000",-1.085053,36.782040
2,4 Bed Villa with En Suite at Masai Lodge Road,"Rudolf Steiner School Ongata Rongai, Masai Lod...",New modern villa for sale.,"KSh 16,000,000",-1.391357,36.789061
3,5 Bed House with En Suite in Ngong Road,"Ngong Road, Ngong, Ngong ward, Kajiado North, ...",5 Bedroom Town House For Sale In Kilimani,"KSh 45,000,000",-1.360530,36.655977
4,5 Bed Townhouse with En Suite in Lavington,"Lavington, Albury, Albury City Council, New So...",Modern 5 Bedroom Townhouse For Sale,"KSh 72,000,000",-36.050799,146.933662
6,5 Bed House with En Suite in Lavington,"Lavington, Albury, Albury City Council, New So...",Rustic 5 Bedroom house For Sale on 1/4 of an a...,"KSh 85,000,000",-36.050799,146.933662

In [ ]:
# Display the first few rows to check the current data type of 'price'
print("Before conversion:")
print(df['selling price'].head())
print("Data type:", df['selling price'].dtype)

Before conversion:
0    KSh 130,000,000
1     KSh 26,950,000
2     KSh 16,000,000
3     KSh 45,000,000
4     KSh 72,000,000
Name: selling price, dtype: object
Data type: object

In [ ]:
# Remove currency symbols and commas (e.g., 'KSh 130,000,000')
df['selling price'] = df['selling price'].str.replace('KSh', '', regex=False)  # Remove 'KSh'
df['selling price'] = df['selling price'].str.replace(',', '', regex=False)     # Remove commas

In [ ]:
# Convert the cleaned column to numeric (float or int)
df['selling price'] = pd.to_numeric(df['selling price'], errors='coerce')  # Convert to float

In [ ]:
# Display the first few rows after conversion
print("\nAfter conversion:")
print(df['selling price'].head())
print("Data type:", df['selling price'].dtype)

After conversion:
0    130000000.0
1     26950000.0
2     16000000.0
3     45000000.0
4     72000000.0
Name: selling price, dtype: float64
Data type: float64

In [ ]:
 df.to_csv('cleaned1_data.csv', index=False)

In [ ]:
df.head()

,House,location,size,selling price,latitude,longitude
0,6 Bed Villa with En Suite at Kiambu Road,"Kiambu Road, Gathanji, Githunguri ward, Githun...","6bdrm Mansion in Mushroom Estate, Kiambu / Kia...",130000000.0,-1.085053,36.782040
1,4 Bed Townhouse with En Suite at Off Kiambu Road,NaN,4 Bedroom with DSQ for Sale,26950000.0,NaN,NaN
2,4 Bed Villa with En Suite at Masai Lodge Road,"Rudolf Steiner School Ongata Rongai, Masai Lod...",New modern villa for sale.,16000000.0,-1.391357,36.789061
3,5 Bed House with En Suite in Ngong Road,"Ngong Road, Ngong, Ngong ward, Kajiado North, ...",5 Bedroom Town House For Sale In Kilimani,45000000.0,-1.360530,36.655977
4,5 Bed Townhouse with En Suite in Lavington,"Lavington, Albury, Albury City Council, New So...",Modern 5 Bedroom Townhouse For Sale,72000000.0,-36.050799,146.933662

In [ ]:
# Remove rows where 'latitude' or 'longitude' contain NA values
df_cleaned2 = df.dropna(subset=['latitude', 'longitude'])

In [ ]:
# Display the cleaned DataFrame
print("\nAfter removing rows with null latitude/longitude:")
print(df_cleaned.head())

# Optional: Save the cleaned DataFrame to a new CSV file
df_cleaned2.to_csv('cleaned2_data.csv', index=False)

After removing rows with null latitude/longitude:
                                           House  \
0       6 Bed Villa with En Suite at Kiambu Road
2  4 Bed Villa with En Suite at Masai Lodge Road
3        5 Bed House with En Suite in Ngong Road
4     5 Bed Townhouse with En Suite in Lavington
6         5 Bed House with En Suite in Lavington

                                            location  \
0  Kiambu Road, Gathanji, Githunguri ward, Githun...
2  Rudolf Steiner School Ongata Rongai, Masai Lod...
3  Ngong Road, Ngong, Ngong ward, Kajiado North, ...
4  Lavington, Albury, Albury City Council, New So...
6  Lavington, Albury, Albury City Council, New So...

                                                size  selling price  \
0  6bdrm Mansion in Mushroom Estate, Kiambu / Kia...    130000000.0
2                         New modern villa for sale.     16000000.0
3          5 Bedroom Town House For Sale In Kilimani     45000000.0
4                Modern 5 Bedroom Townhouse For Sale     72000000.0
6  Rustic 5 Bedroom house For Sale on 1/4 of an a...     85000000.0

    latitude   longitude
0  -1.085053   36.782040
2  -1.391357   36.789061
3  -1.360530   36.655977
4 -36.050799  146.933662
6 -36.050799  146.933662

In [ ]:
df_cleaned2.head()

,House,location,size,selling price,latitude,longitude
0,6 Bed Villa with En Suite at Kiambu Road,"Kiambu Road, Gathanji, Githunguri ward, Githun...","6bdrm Mansion in Mushroom Estate, Kiambu / Kia...",130000000.0,-1.085053,36.782040
2,4 Bed Villa with En Suite at Masai Lodge Road,"Rudolf Steiner School Ongata Rongai, Masai Lod...",New modern villa for sale.,16000000.0,-1.391357,36.789061
3,5 Bed House with En Suite in Ngong Road,"Ngong Road, Ngong, Ngong ward, Kajiado North, ...",5 Bedroom Town House For Sale In Kilimani,45000000.0,-1.360530,36.655977
4,5 Bed Townhouse with En Suite in Lavington,"Lavington, Albury, Albury City Council, New So...",Modern 5 Bedroom Townhouse For Sale,72000000.0,-36.050799,146.933662
6,5 Bed House with En Suite in Lavington,"Lavington, Albury, Albury City Council, New So...",Rustic 5 Bedroom house For Sale on 1/4 of an a...,85000000.0,-36.050799,146.933662